version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bootcamp
      MYSQL_DATABASE: bootcamp
      MYSQL_USER: bootcamp
      MYSQL_PASSWORD: bootcamp
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    restart: always
volumes:
  mysql: null